<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <%@include file="head.jsp" %>
        <title>MDA's blog</title>
    </head>
    <body>
        <div id="title">
            <h1>MDA's blog!</h1>
        </div>
        <%@include file="menu.jsp"%>
        <%@include file="message.jsp"%>
        <div id="content">
            <p>
                This is an example built using <a href="">this EJBs</a>, that was generated by our tool <a href="http://code.google.com/p/umltoejb/">UMLToEJB</a>.
            </p>
            <p>
                If you want more information about us, please visit <a href="http://mda.ic.uff.br">our group's website</a>.
            </p>
            <p>
                If you want more information about this tool, please visit <a href="http://code.google.com/p/umltoejb/">this project website</a>.
            </p>
            <br/>
            <p>
            -- Dev Team
            </p>
        </div>
        <%@include file="foot.jsp" %>
    </body>
</html>
